language: node_js
node_js: 
  - "12.14"
branches:
  only:
    - main
script:
  - npm install
  - npm run build
before_install:
  - cd app
  - npm install - g firebase-tools
after_success: 
  - firebase deploy --token $FIREBASE_TOKEN --only hosting:tixlab
